package com.englishcenter.core.utils.enums;

public class ExceptionEnum {
    public static final String classroom_exist = "classroom_exist";
    public static final String room_exist = "room_exist";
    public static final String shift_exist = "shift_exist";
    public static final String course_exist = "course_exist";
    public static final String category_course_exist = "category_course_exist";
    public static final String absent_exist = "absent_exist";
    public static final String cannot_register_absent = "cannot_register_absent";
    public static final String not_during_muster_time = "not_during_muster_time";
    public static final String cannot_connect = "cannot_connect";
    public static final String exam_schedule_exist = "exam_schedule_exist";
    public static final String receptionist_not_available = "receptionist_not_available";
    public static final String room_capacity_is_not_enough = "room_capacity_is_not_enough";
    public static final String can_not_update = "can_not_update";
    public static final String cannot_when_status_not_is_create = "cannot_when_status_not_is_create";
    public static final String can_only_generate_with_status_is_create = "can_only_generate_with_status_is_create";
    public static final String cannot_when_status_not_is_register = "cannot_when_status_not_is_register";
    public static final String phone_number_used = "phone_number_used";
    public static final String room_not_empty = "room_not_empty";
    public static final String teacher_not_available = "teacher_not_available";
    public static final String schedule_not_exist = "schedule_not_exist";
    public static final String schedule_exist = "schedule_exist";
    public static final String param_not_null = "param_not_null";
    public static final String member_exist = "member_exist";
    public static final String member_not_exist = "member_not_exist";
    public static final String category_course_not_exist = "category_course_not_exist";
    public static final String course_not_exist = "course_not_exist";
    public static final String password_incorrect = "password_incorrect";
    public static final String confirm_password_incorrect = "confirm_password_incorrect";
    public static final String member_type_deny = "member_type_deny";
    public static final String shift_not_exist = "shift_not_exist";
    public static final String room_not_exist = "room_not_exist";
    public static final String document_not_exist = "document_not_exist";
    public static final String document_extension_not_match = "document_extension_not_match";
    public static final String start_date_not_allow = "start_date_not_allow";
    public static final String classroom_not_exist = "classroom_not_exist";
    public static final String exam_schedule_not_exist = "exam_schedule_not_exist";
    public static final String room_not_available = "room_not_available";
    public static final String class_full = "class_full";
    public static final String input_score_not_enough = "input_score_not_enough";
    public static final String unsubscribe_timeout = "unsubscribe_timeout";
    public static final String register_not_in_time_register = "register_not_in_time_register";
    public static final String register_already = "register_already";
    public static final String exam_schedule_conflict = "exam_schedule_conflict";
    public static final String class_registered = "class_registered";
}
